import styles from '@/styles/Home.module.css'
// import Header from '@/layout/header/header'
import WebHome from '../component/home/webHome'


export default function Home() {
  return (
    <>
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      <WebHome />
    </>
  )
}
